# basic config
start_date: "2020-01-01"
end_date: null          # null -> today
horizon_days: 3         # label look-ahead in trading days

universe: "sp500"
tickers_file: "data/tickers.txt"

# gplearn search
population_size: 600
generations: 10
tournament_size: 7
stopping_criteria: 0.15
const_range: [-0.2, 0.2]
parsimony_coefficient: 0.0005
metric: "rank_ic"       # custom fitness

# genetic operators
p_crossover: 0.65
p_subtree_mutation: 0.18
p_point_mutation: 0.10
p_hoist_mutation: 0.04

# evaluation
top_quantile: 0.2
bottom_quantile: 0.2
embargo_days: 5         # gap between train/valid/test splits
min_group_size: 30      # min #stocks in a day to count IC

# backtest
cost_bps_oneway: 1.0    # 1bp per side, set 0 for frictionless
